### ISSUE TITLE
URL de login dejo de funcionar, Solucionado

### ISSUE THREAD

**Issue by alexdlr** [blacktrue/sat-scraper#1]
**# Error que marca:**

( ! ) Fatal error: Uncaught exception 'GuzzleHttp\Exception\ClientException' with message ' in C:\wamp64\www\zat\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php on line 111
( ! ) GuzzleHttp\Exception\ClientException: Client error: `POST https://cfdicontribuyentes.accesscontrol.windows.net/v2/wsfederation` resulted in a `400 Bad Request` response: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> <html (truncated...) in C:\wamp64\www\zat\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php on line 111

**# Solucion** 
cambiar esta constante 

const SAT_URL_LOGIN = 'https://cfdiau.sat.gob.mx/nidp/app/login?id=mat-ptsc-totp&sid=0&option=credential';

por 

const SAT_URL_LOGIN = 'https://cfdiau.sat.gob.mx//nidp/app/login?id=20&sid=1&option=credential&sid=1';

**Comment by blacktrue** [comment]
Hola

Gracias por el aporte!

Cambie la URL y subí un nueva versión (1.2.0)
