### ISSUE TITLE
Error downloadPeriod

### ISSUE THREAD

**Issue by lfjaimesb** [blacktrue/sat-scraper#2]
Client error: `POST https://cfdicontribuyentes.accesscontrol.windows.net/v2/wsfederation` resulted in a `400 Bad Request` response:

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html (truncated...)

**Comment by blacktrue** [comment]
Hola, este error generalmente se debe a que la URL de login libre de captcha ya cambio.

En la versión v1.4.0, agregue un parametro en el constructor para sobrescribir el valor.
En la versión v2.0.0 controlamos el error lanzando una excepción: SATAuthenticatedException

Favor de revisar la documentación del readme
