### ISSUE TITLE
Blacktrue \ Scraping \ Exceptions \ SATAuthenticatedException Error al autenticar al usuario, posible cambio en el metodo

### ISSUE THREAD

**Issue by josh10pue** [blacktrue/sat-scraper#3]
this problem with url 
'loginUrl' => 'https://cfdiau.sat.gob.mx/nidp/app/login?id=4&sid=1&option=credential'

**Comment by gabLez** [comment]
you could solve it???

**Comment by blacktrue** [comment]
The URL changes constantly by decision of the authority, if you get a correct url the library will work
